// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(42,23,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(12,167,2^(35.371767))
// 
// Ring
// degree d = 64
// modulus q = 73786976294838208621, log(q) ~ 66.0
// factors q = q1
// 
// Compression
// D = 12
// gamma = 1702716, log(gamma) ~ 20.699406
// 
// Dimensions of secrets
// s1: m1 = 102
// m: l = 0
// s2: m2 = 65
// 
// Size of secrets
// l2(s1) <= alpha = 81.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [102], bounds: [80.79604])
// approximate infinity: yes (psi: 2106.3506, dimension: 24, bound: 3264.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 203161.6, log(stdev4/1.55) = 17.0
// 
// Repetition rate
// M1 = 2.1204816
// M2 = 2.7495318
// M3 = 1.0279403
// M4 = 1.0444663
// total = 6.2597303
// 
// Security
// MSIS dimension: 12
// MSIS root hermite factor: 1.0042865
// MLWE dimension: 42
// MLWE root hermite factor: 1.0043229
// 
// Proof size
// ~ 36.3671875000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _client_param_q_limbs[] = {2157UL, 4UL};
static const int_t _client_param_q = {{(limb_t *)_client_param_q_limbs, 2, 0}};
static const limb_t _client_param_qminus1_limbs[] = {2156UL, 4UL};
static const int_t _client_param_qminus1 = {{(limb_t *)_client_param_qminus1_limbs, 2, 0}};
static const limb_t _client_param_m_limbs[] = {43334869875445UL, 0UL};
static const int_t _client_param_m = {{(limb_t *)_client_param_m_limbs, 2, 0}};
static const limb_t _client_param_mby2_limbs[] = {21667434937722UL, 0UL};
static const int_t _client_param_mby2 = {{(limb_t *)_client_param_mby2_limbs, 2, 0}};
static const limb_t _client_param_gamma_limbs[] = {1702716UL, 0UL};
static const int_t _client_param_gamma = {{(limb_t *)_client_param_gamma_limbs, 2, 0}};
static const limb_t _client_param_gammaby2_limbs[] = {851358UL, 0UL};
static const int_t _client_param_gammaby2 = {{(limb_t *)_client_param_gammaby2_limbs, 2, 0}};
static const limb_t _client_param_pow2D_limbs[] = {4096UL, 0UL};
static const int_t _client_param_pow2D = {{(limb_t *)_client_param_pow2D_limbs, 2, 0}};
static const limb_t _client_param_pow2Dby2_limbs[] = {2048UL, 0UL};
static const int_t _client_param_pow2Dby2 = {{(limb_t *)_client_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _client_param_Bsq_limbs[] = {1031594339808106UL, 0UL, 0UL, 0UL};
static const int_t _client_param_Bsq = {{(limb_t *)_client_param_Bsq_limbs, 4, 0}};
static const limb_t _client_param_scM1_limbs[] = {5858801768933948483UL, 2222493620260265026UL, 2UL};
static const int_t _client_param_scM1 = {{(limb_t *)_client_param_scM1_limbs, 3, 0}};
static const limb_t _client_param_scM2_limbs[] = {14165351592000519905UL, 13826422118645399154UL, 2UL};
static const int_t _client_param_scM2 = {{(limb_t *)_client_param_scM2_limbs, 3, 0}};
static const limb_t _client_param_scM3_limbs[] = {15716771392927436776UL, 515408086451080670UL, 1UL};
static const int_t _client_param_scM3 = {{(limb_t *)_client_param_scM3_limbs, 3, 0}};
static const limb_t _client_param_scM4_limbs[] = {2648320286749286565UL, 820259372395588588UL, 1UL};
static const int_t _client_param_scM4 = {{(limb_t *)_client_param_scM4_limbs, 3, 0}};
static const limb_t _client_param_stdev1sq_limbs[] = {41274635715UL, 0UL, 0UL, 0UL};
static const int_t _client_param_stdev1sq = {{(limb_t *)_client_param_stdev1sq_limbs, 4, 0}};
static const limb_t _client_param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _client_param_stdev2sq = {{(limb_t *)_client_param_stdev2sq_limbs, 4, 0}};
static const limb_t _client_param_stdev3sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _client_param_stdev3sq = {{(limb_t *)_client_param_stdev3sq_limbs, 4, 0}};
static const limb_t _client_param_stdev4sq_limbs[] = {41274635715UL, 0UL, 0UL, 0UL};
static const int_t _client_param_stdev4sq = {{(limb_t *)_client_param_stdev4sq_limbs, 4, 0}};
static const limb_t _client_param_inv2_limbs[] = {1078UL, 2UL};
static const int_t _client_param_inv2 = {{(limb_t *)_client_param_inv2_limbs, 2, 1}};
static const limb_t _client_param_inv4_limbs[] = {539UL, 1UL};
static const int_t _client_param_inv4 = {{(limb_t *)_client_param_inv4_limbs, 2, 1}};
static const unsigned int _client_param_n[1] = {102};
static const limb_t _client_param_Bz3sqr_limbs[] = {27753065054UL, 0UL, 0UL, 0UL};
static const int_t _client_param_Bz3sqr = {{(limb_t *)_client_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _client_param_Bz4_limbs[] = {3250585UL, 0UL};
static const int_t _client_param_Bz4 = {{(limb_t *)_client_param_Bz4_limbs, 2, 0}};
static const limb_t _client_param_Pmodq_limbs[] = {15918711730628524731UL, 1UL};
static const int_t _client_param_Pmodq = {{(limb_t *)_client_param_Pmodq_limbs, 2, 0}};
static const limb_t _client_param_l2Bsq0_limbs[] = {6528UL, 0UL};
static const int_t _client_param_l2Bsq0 = {{(limb_t *)_client_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _client_param_Ppmodq_0_limbs[] = {8644696541702086143UL, 0UL};
static const int_t _client_param_Ppmodq_0 = {{(limb_t *)_client_param_Ppmodq_0_limbs, 2, 1}};
static const limb_t _client_param_Ppmodq_1_limbs[] = {7635890225175566975UL, 0UL};
static const int_t _client_param_Ppmodq_1 = {{(limb_t *)_client_param_Ppmodq_1_limbs, 2, 1}};
static const limb_t _client_param_Ppmodq_2_limbs[] = {5041816839814287743UL, 0UL};
static const int_t _client_param_Ppmodq_2 = {{(limb_t *)_client_param_Ppmodq_2_limbs, 2, 1}};
static const int_srcptr _client_param_l2Bsq[] = {_client_param_l2Bsq0};
static const int_srcptr _client_param_Ppmodq[] = {_client_param_Ppmodq_0, _client_param_Ppmodq_1, _client_param_Ppmodq_2};
static const polyring_t _client_param_ring = {{_client_param_q, 64, 67, 6, moduli_d64, 3, _client_param_Pmodq, _client_param_Ppmodq, _client_param_inv2}};
static const dcompress_params_t _client_param_dcomp = {{ _client_param_q, _client_param_qminus1, _client_param_m, _client_param_mby2, _client_param_gamma, _client_param_gammaby2, _client_param_pow2D, _client_param_pow2Dby2, 12, 1, 46 }};
static const abdlop_params_t _client_param_tbox = {{ _client_param_ring, _client_param_dcomp, 103, 65, 0, 11, 12, _client_param_Bsq, 1, 8, 5, 140, 1, 17, _client_param_scM1, _client_param_stdev1sq, 2, 12, _client_param_scM2, _client_param_stdev2sq}};
static const abdlop_params_t _client_param_quad_eval_ = {{ _client_param_ring, _client_param_dcomp, 103, 65, 9, 2, 12, _client_param_Bsq, 1, 8, 5, 140, 1, 17, _client_param_scM1, _client_param_stdev1sq, 2, 12, _client_param_scM2, _client_param_stdev2sq}};
static const abdlop_params_t _client_param_quad_many_ = {{ _client_param_ring, _client_param_dcomp, 103, 65, 10, 1, 12, _client_param_Bsq, 1, 8, 5, 140, 1, 17, _client_param_scM1, _client_param_stdev1sq, 2, 12, _client_param_scM2, _client_param_stdev2sq}};
static const lnp_quad_eval_params_t _client_param_quad_eval = {{ _client_param_quad_eval_, _client_param_quad_many_, 2}};
static const lnp_tbox_params_t _client_param = {{ _client_param_tbox, _client_param_quad_eval, 0, _client_param_n, 24, 1, 103, 2, 12, _client_param_scM3, _client_param_stdev3sq, 2, 17, _client_param_scM4, _client_param_stdev4sq, _client_param_Bz3sqr, _client_param_Bz4, &_client_param_l2Bsq[0], _client_param_inv4, 37240UL }};

static const unsigned int client_param_Es0[102] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101};
static const unsigned int *client_param_Es[1] = { client_param_Es0, };
static const unsigned int client_param_Es_nrows[1] = {102};

static const limb_t client_param_p_limbs[] = {2199023255579UL};
static const int_t client_param_p = {{(limb_t *)client_param_p_limbs, 1, 0}};
static const limb_t client_param_pinv_limbs[] = {15092058693928518123UL, 0UL};
static const int_t client_param_pinv = {{(limb_t *)client_param_pinv_limbs, 2, 0}};
static const unsigned int client_param_s1_indices[102] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101};
static const lin_params_t client_param = {{ _client_param, 64, client_param_p, client_param_pinv, 1, client_param_s1_indices, 102, NULL, 0,  NULL, 0, client_param_Es, client_param_Es_nrows, NULL, NULL }};

