// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(41,22,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(11,139,2^(33.79207))
// 
// Ring
// degree d = 64
// modulus q = 36893488147419103693, log(q) ~ 65.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 453378, log(gamma) ~ 18.790355
// 
// Dimensions of secrets
// s1: m1 = 76
// m: l = 0
// s2: m2 = 63
// 
// Size of secrets
// l2(s1) <= alpha = 70.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [24, 51, 1], bounds: [39.191836, 57.131427, 8.0])
// approximate infinity: yes (psi: 2826.7961, dimension: 52, bound: 2432.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 203161.6, log(stdev4/1.55) = 17.0
// 
// Repetition rate
// M1 = 3.7434587
// M2 = 2.6652816
// M3 = 1.021361
// M4 = 1.02445
// total = 10.439656
// 
// Security
// MSIS dimension: 11
// MSIS root hermite factor: 1.0043336
// MLWE dimension: 41
// MLWE root hermite factor: 1.0043564
// 
// Proof size
// ~ 31.2324218750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _server_param_q_limbs[] = {461UL, 2UL};
static const int_t _server_param_q = {{(limb_t *)_server_param_q_limbs, 2, 0}};
static const limb_t _server_param_qminus1_limbs[] = {460UL, 2UL};
static const int_t _server_param_qminus1 = {{(limb_t *)_server_param_qminus1_limbs, 2, 0}};
static const limb_t _server_param_m_limbs[] = {81374676643814UL, 0UL};
static const int_t _server_param_m = {{(limb_t *)_server_param_m_limbs, 2, 0}};
static const limb_t _server_param_mby2_limbs[] = {40687338321907UL, 0UL};
static const int_t _server_param_mby2 = {{(limb_t *)_server_param_mby2_limbs, 2, 0}};
static const limb_t _server_param_gamma_limbs[] = {453378UL, 0UL};
static const int_t _server_param_gamma = {{(limb_t *)_server_param_gamma_limbs, 2, 0}};
static const limb_t _server_param_gammaby2_limbs[] = {226689UL, 0UL};
static const int_t _server_param_gammaby2 = {{(limb_t *)_server_param_gammaby2_limbs, 2, 0}};
static const limb_t _server_param_pow2D_limbs[] = {1024UL, 0UL};
static const int_t _server_param_pow2D = {{(limb_t *)_server_param_pow2D_limbs, 2, 0}};
static const limb_t _server_param_pow2Dby2_limbs[] = {512UL, 0UL};
static const int_t _server_param_pow2Dby2 = {{(limb_t *)_server_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _server_param_Bsq_limbs[] = {72024840739156UL, 0UL, 0UL, 0UL};
static const int_t _server_param_Bsq = {{(limb_t *)_server_param_Bsq_limbs, 4, 0}};
static const limb_t _server_param_scM1_limbs[] = {8226843651112521785UL, 13714392622969192212UL, 3UL};
static const int_t _server_param_scM1 = {{(limb_t *)_server_param_scM1_limbs, 3, 0}};
static const limb_t _server_param_scM2_limbs[] = {14122598965936230364UL, 12272279291762237568UL, 2UL};
static const int_t _server_param_scM2 = {{(limb_t *)_server_param_scM2_limbs, 3, 0}};
static const limb_t _server_param_scM3_limbs[] = {4183998216138786290UL, 394040732677287645UL, 1UL};
static const int_t _server_param_scM3 = {{(limb_t *)_server_param_scM3_limbs, 3, 0}};
static const limb_t _server_param_scM4_limbs[] = {3199606511312032710UL, 451022296578399073UL, 1UL};
static const int_t _server_param_scM4 = {{(limb_t *)_server_param_scM4_limbs, 3, 0}};
static const limb_t _server_param_stdev1sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t _server_param_stdev1sq = {{(limb_t *)_server_param_stdev1sq_limbs, 4, 0}};
static const limb_t _server_param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _server_param_stdev2sq = {{(limb_t *)_server_param_stdev2sq_limbs, 4, 0}};
static const limb_t _server_param_stdev3sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _server_param_stdev3sq = {{(limb_t *)_server_param_stdev3sq_limbs, 4, 0}};
static const limb_t _server_param_stdev4sq_limbs[] = {41274635715UL, 0UL, 0UL, 0UL};
static const int_t _server_param_stdev4sq = {{(limb_t *)_server_param_stdev4sq_limbs, 4, 0}};
static const limb_t _server_param_inv2_limbs[] = {230UL, 1UL};
static const int_t _server_param_inv2 = {{(limb_t *)_server_param_inv2_limbs, 2, 1}};
static const limb_t _server_param_inv4_limbs[] = {9223372036854775923UL};
static const int_t _server_param_inv4 = {{(limb_t *)_server_param_inv4_limbs, 1, 1}};
static const unsigned int _server_param_n[3] = {24, 51, 1};
static const limb_t _server_param_Bz3sqr_limbs[] = {27753065054UL, 0UL, 0UL, 0UL};
static const int_t _server_param_Bz3sqr = {{(limb_t *)_server_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _server_param_Bz4_limbs[] = {3250585UL, 0UL};
static const int_t _server_param_Bz4 = {{(limb_t *)_server_param_Bz4_limbs, 2, 0}};
static const limb_t _server_param_Pmodq_limbs[] = {2728938423809685976UL, 0UL};
static const int_t _server_param_Pmodq = {{(limb_t *)_server_param_Pmodq_limbs, 2, 1}};
static const limb_t _server_param_l2Bsq0_limbs[] = {1536UL, 0UL};
static const int_t _server_param_l2Bsq0 = {{(limb_t *)_server_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _server_param_l2Bsq1_limbs[] = {3264UL, 0UL};
static const int_t _server_param_l2Bsq1 = {{(limb_t *)_server_param_l2Bsq1_limbs, 2, 0}};
static const limb_t _server_param_l2Bsq2_limbs[] = {64UL, 0UL};
static const int_t _server_param_l2Bsq2 = {{(limb_t *)_server_param_l2Bsq2_limbs, 2, 0}};
static const limb_t _server_param_Ppmodq_0_limbs[] = {8644675324563643903UL, 0UL};
static const int_t _server_param_Ppmodq_0 = {{(limb_t *)_server_param_Ppmodq_0_limbs, 2, 1}};
static const limb_t _server_param_Ppmodq_1_limbs[] = {7635869008037124735UL, 0UL};
static const int_t _server_param_Ppmodq_1 = {{(limb_t *)_server_param_Ppmodq_1_limbs, 2, 1}};
static const limb_t _server_param_Ppmodq_2_limbs[] = {5041795622675845503UL, 0UL};
static const int_t _server_param_Ppmodq_2 = {{(limb_t *)_server_param_Ppmodq_2_limbs, 2, 1}};
static const int_srcptr _server_param_l2Bsq[] = {_server_param_l2Bsq0, _server_param_l2Bsq1, _server_param_l2Bsq2};
static const int_srcptr _server_param_Ppmodq[] = {_server_param_Ppmodq_0, _server_param_Ppmodq_1, _server_param_Ppmodq_2};
static const polyring_t _server_param_ring = {{_server_param_q, 64, 66, 6, moduli_d64, 3, _server_param_Pmodq, _server_param_Ppmodq, _server_param_inv2}};
static const dcompress_params_t _server_param_dcomp = {{ _server_param_q, _server_param_qminus1, _server_param_m, _server_param_mby2, _server_param_gamma, _server_param_gammaby2, _server_param_pow2D, _server_param_pow2Dby2, 10, 0, 47 }};
static const abdlop_params_t _server_param_tbox = {{ _server_param_ring, _server_param_dcomp, 79, 63, 0, 11, 11, _server_param_Bsq, 1, 8, 5, 140, 1, 16, _server_param_scM1, _server_param_stdev1sq, 2, 12, _server_param_scM2, _server_param_stdev2sq}};
static const abdlop_params_t _server_param_quad_eval_ = {{ _server_param_ring, _server_param_dcomp, 79, 63, 9, 2, 11, _server_param_Bsq, 1, 8, 5, 140, 1, 16, _server_param_scM1, _server_param_stdev1sq, 2, 12, _server_param_scM2, _server_param_stdev2sq}};
static const abdlop_params_t _server_param_quad_many_ = {{ _server_param_ring, _server_param_dcomp, 79, 63, 10, 1, 11, _server_param_Bsq, 1, 8, 5, 140, 1, 16, _server_param_scM1, _server_param_stdev1sq, 2, 12, _server_param_scM2, _server_param_stdev2sq}};
static const lnp_quad_eval_params_t _server_param_quad_eval = {{ _server_param_quad_eval_, _server_param_quad_many_, 2}};
static const lnp_tbox_params_t _server_param = {{ _server_param_tbox, _server_param_quad_eval, 0, _server_param_n, 52, 3, 79, 2, 12, _server_param_scM3, _server_param_stdev3sq, 2, 17, _server_param_scM4, _server_param_stdev4sq, _server_param_Bz3sqr, _server_param_Bz4, &_server_param_l2Bsq[0], _server_param_inv4, 31982UL }};

static const unsigned int server_param_Es0[24] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const unsigned int server_param_Es1[51] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74};
static const unsigned int server_param_Es2[1] = {75};
static const unsigned int *server_param_Es[3] = { server_param_Es0, server_param_Es1, server_param_Es2, };
static const unsigned int server_param_Es_nrows[3] = {24, 51, 1};

static const limb_t server_param_p_limbs[] = {2199023255579UL};
static const int_t server_param_p = {{(limb_t *)server_param_p_limbs, 1, 0}};
static const limb_t server_param_pinv_limbs[] = {9593674919057203235UL, 0UL};
static const int_t server_param_pinv = {{(limb_t *)server_param_pinv_limbs, 2, 0}};
static const unsigned int server_param_s1_indices[76] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75};
static const lin_params_t server_param = {{ _server_param, 64, server_param_p, server_param_pinv, 1, server_param_s1_indices, 76, NULL, 0,  NULL, 0, server_param_Es, server_param_Es_nrows, NULL, NULL }};

