// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(51,27,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(16,154,2^(45.518938))
// 
// Ring
// degree d = 64
// modulus q = 2417851639229258349412453, log(q) ~ 81.0
// factors q = q1
// 
// Compression
// D = 22
// gamma = 1912520502, log(gamma) ~ 30.832828
// 
// Dimensions of secrets
// s1: m1 = 76
// m: l = 0
// s2: m2 = 78
// 
// Size of secrets
// l2(s1) <= alpha = 90102.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [76], bounds: [90101.716])
// approximate infinity: yes (psi: 2947.2252, dimension: 52, bound: 1.5290227e+8)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 208037478.4, log(stdev1/1.55) = 27.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6501171.2, log(stdev3/1.55) = 22.0
// stdev4 = 13314398617.6, log(stdev4/1.55) = 33.0
// 
// Repetition rate
// M1 = 2.2539715
// M2 = 3.365972
// M3 = 1.032895
// M4 = 1.0224708
// total = 8.0124629
// 
// Security
// MSIS dimension: 16
// MSIS root hermite factor: 1.0043382
// MLWE dimension: 51
// MLWE root hermite factor: 1.0043564
// 
// Proof size
// ~ 43.8750000000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241]
// bit length of products: [49, 99, 149, 199]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893]

#include "lazer.h"
static const limb_t _server_gaussian_param_q_limbs[] = {101UL, 131072UL};
static const int_t _server_gaussian_param_q = {{(limb_t *)_server_gaussian_param_q_limbs, 2, 0}};
static const limb_t _server_gaussian_param_qminus1_limbs[] = {100UL, 131072UL};
static const int_t _server_gaussian_param_qminus1 = {{(limb_t *)_server_gaussian_param_qminus1_limbs, 2, 0}};
static const limb_t _server_gaussian_param_m_limbs[] = {1264222598764726UL, 0UL};
static const int_t _server_gaussian_param_m = {{(limb_t *)_server_gaussian_param_m_limbs, 2, 0}};
static const limb_t _server_gaussian_param_mby2_limbs[] = {632111299382363UL, 0UL};
static const int_t _server_gaussian_param_mby2 = {{(limb_t *)_server_gaussian_param_mby2_limbs, 2, 0}};
static const limb_t _server_gaussian_param_gamma_limbs[] = {1912520502UL, 0UL};
static const int_t _server_gaussian_param_gamma = {{(limb_t *)_server_gaussian_param_gamma_limbs, 2, 0}};
static const limb_t _server_gaussian_param_gammaby2_limbs[] = {956260251UL, 0UL};
static const int_t _server_gaussian_param_gammaby2 = {{(limb_t *)_server_gaussian_param_gammaby2_limbs, 2, 0}};
static const limb_t _server_gaussian_param_pow2D_limbs[] = {4194304UL, 0UL};
static const int_t _server_gaussian_param_pow2D = {{(limb_t *)_server_gaussian_param_pow2D_limbs, 2, 0}};
static const limb_t _server_gaussian_param_pow2Dby2_limbs[] = {2097152UL, 0UL};
static const int_t _server_gaussian_param_pow2Dby2 = {{(limb_t *)_server_gaussian_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _server_gaussian_param_Bsq_limbs[] = {13276293186838349103UL, 86UL, 0UL, 0UL};
static const int_t _server_gaussian_param_Bsq = {{(limb_t *)_server_gaussian_param_Bsq_limbs, 4, 0}};
static const limb_t _server_gaussian_param_scM1_limbs[] = {6597237808515367682UL, 4684947960161443053UL, 2UL};
static const int_t _server_gaussian_param_scM1 = {{(limb_t *)_server_gaussian_param_scM1_limbs, 3, 0}};
static const limb_t _server_gaussian_param_scM2_limbs[] = {17218260138372021781UL, 6750992661786295575UL, 3UL};
static const int_t _server_gaussian_param_scM2 = {{(limb_t *)_server_gaussian_param_scM2_limbs, 3, 0}};
static const limb_t _server_gaussian_param_scM3_limbs[] = {13831422433523406787UL, 606805610968543947UL, 1UL};
static const int_t _server_gaussian_param_scM3 = {{(limb_t *)_server_gaussian_param_scM3_limbs, 3, 0}};
static const limb_t _server_gaussian_param_scM4_limbs[] = {10743373642008059388UL, 414513612067102771UL, 1UL};
static const int_t _server_gaussian_param_scM4 = {{(limb_t *)_server_gaussian_param_scM4_limbs, 3, 0}};
static const limb_t _server_gaussian_param_stdev1sq_limbs[] = {43279592419030467UL, 0UL, 0UL, 0UL};
static const int_t _server_gaussian_param_stdev1sq = {{(limb_t *)_server_gaussian_param_stdev1sq_limbs, 4, 0}};
static const limb_t _server_gaussian_param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _server_gaussian_param_stdev2sq = {{(limb_t *)_server_gaussian_param_stdev2sq_limbs, 4, 0}};
static const limb_t _server_gaussian_param_stdev3sq_limbs[] = {42265226971709UL, 0UL, 0UL, 0UL};
static const int_t _server_gaussian_param_stdev3sq = {{(limb_t *)_server_gaussian_param_stdev3sq_limbs, 4, 0}};
static const limb_t _server_gaussian_param_stdev4sq_limbs[] = {11252513884962826486UL, 9UL, 0UL, 0UL};
static const int_t _server_gaussian_param_stdev4sq = {{(limb_t *)_server_gaussian_param_stdev4sq_limbs, 4, 0}};
static const limb_t _server_gaussian_param_inv2_limbs[] = {50UL, 65536UL};
static const int_t _server_gaussian_param_inv2 = {{(limb_t *)_server_gaussian_param_inv2_limbs, 2, 1}};
static const limb_t _server_gaussian_param_inv4_limbs[] = {25UL, 32768UL};
static const int_t _server_gaussian_param_inv4 = {{(limb_t *)_server_gaussian_param_inv4_limbs, 2, 1}};
static const unsigned int _server_gaussian_param_n[1] = {76};
static const limb_t _server_gaussian_param_Bz3sqr_limbs[] = {29101197942556085UL, 0UL, 0UL, 0UL};
static const int_t _server_gaussian_param_Bz3sqr = {{(limb_t *)_server_gaussian_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _server_gaussian_param_Bz4_limbs[] = {213030377881UL, 0UL};
static const int_t _server_gaussian_param_Bz4 = {{(limb_t *)_server_gaussian_param_Bz4_limbs, 2, 0}};
static const limb_t _server_gaussian_param_Pmodq_limbs[] = {4897964559688381874UL, 8049UL};
static const int_t _server_gaussian_param_Pmodq = {{(limb_t *)_server_gaussian_param_Pmodq_limbs, 2, 0}};
static const limb_t _server_gaussian_param_l2Bsq0_limbs[] = {8118319137UL, 0UL};
static const int_t _server_gaussian_param_l2Bsq0 = {{(limb_t *)_server_gaussian_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _server_gaussian_param_Ppmodq_0_limbs[] = {1156300258722210305UL, 5264UL};
static const int_t _server_gaussian_param_Ppmodq_0 = {{(limb_t *)_server_gaussian_param_Ppmodq_0_limbs, 2, 0}};
static const limb_t _server_gaussian_param_Ppmodq_1_limbs[] = {3173912917601953153UL, 4095UL};
static const int_t _server_gaussian_param_Ppmodq_1 = {{(limb_t *)_server_gaussian_param_Ppmodq_1_limbs, 2, 0}};
static const limb_t _server_gaussian_param_Ppmodq_2_limbs[] = {8362059633932709505UL, 1539UL};
static const int_t _server_gaussian_param_Ppmodq_2 = {{(limb_t *)_server_gaussian_param_Ppmodq_2_limbs, 2, 0}};
static const limb_t _server_gaussian_param_Ppmodq_3_limbs[] = {2878925584402572543UL, 1574UL};
static const int_t _server_gaussian_param_Ppmodq_3 = {{(limb_t *)_server_gaussian_param_Ppmodq_3_limbs, 2, 1}};
static const int_srcptr _server_gaussian_param_l2Bsq[] = {_server_gaussian_param_l2Bsq0};
static const int_srcptr _server_gaussian_param_Ppmodq[] = {_server_gaussian_param_Ppmodq_0, _server_gaussian_param_Ppmodq_1, _server_gaussian_param_Ppmodq_2, _server_gaussian_param_Ppmodq_3};
static const polyring_t _server_gaussian_param_ring = {{_server_gaussian_param_q, 64, 82, 6, moduli_d64, 4, _server_gaussian_param_Pmodq, _server_gaussian_param_Ppmodq, _server_gaussian_param_inv2}};
static const dcompress_params_t _server_gaussian_param_dcomp = {{ _server_gaussian_param_q, _server_gaussian_param_qminus1, _server_gaussian_param_m, _server_gaussian_param_mby2, _server_gaussian_param_gamma, _server_gaussian_param_gammaby2, _server_gaussian_param_pow2D, _server_gaussian_param_pow2Dby2, 22, 0, 51 }};
static const abdlop_params_t _server_gaussian_param_tbox = {{ _server_gaussian_param_ring, _server_gaussian_param_dcomp, 77, 78, 0, 11, 16, _server_gaussian_param_Bsq, 1, 8, 5, 140, 1, 27, _server_gaussian_param_scM1, _server_gaussian_param_stdev1sq, 2, 12, _server_gaussian_param_scM2, _server_gaussian_param_stdev2sq}};
static const abdlop_params_t _server_gaussian_param_quad_eval_ = {{ _server_gaussian_param_ring, _server_gaussian_param_dcomp, 77, 78, 9, 2, 16, _server_gaussian_param_Bsq, 1, 8, 5, 140, 1, 27, _server_gaussian_param_scM1, _server_gaussian_param_stdev1sq, 2, 12, _server_gaussian_param_scM2, _server_gaussian_param_stdev2sq}};
static const abdlop_params_t _server_gaussian_param_quad_many_ = {{ _server_gaussian_param_ring, _server_gaussian_param_dcomp, 77, 78, 10, 1, 16, _server_gaussian_param_Bsq, 1, 8, 5, 140, 1, 27, _server_gaussian_param_scM1, _server_gaussian_param_stdev1sq, 2, 12, _server_gaussian_param_scM2, _server_gaussian_param_stdev2sq}};
static const lnp_quad_eval_params_t _server_gaussian_param_quad_eval = {{ _server_gaussian_param_quad_eval_, _server_gaussian_param_quad_many_, 2}};
static const lnp_tbox_params_t _server_gaussian_param = {{ _server_gaussian_param_tbox, _server_gaussian_param_quad_eval, 0, _server_gaussian_param_n, 52, 1, 77, 2, 22, _server_gaussian_param_scM3, _server_gaussian_param_stdev3sq, 2, 33, _server_gaussian_param_scM4, _server_gaussian_param_stdev4sq, _server_gaussian_param_Bz3sqr, _server_gaussian_param_Bz4, &_server_gaussian_param_l2Bsq[0], _server_gaussian_param_inv4, 44928UL }};

static const unsigned int server_gaussian_param_Es0[76] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75};
static const unsigned int *server_gaussian_param_Es[1] = { server_gaussian_param_Es0, };
static const unsigned int server_gaussian_param_Es_nrows[1] = {76};

static const limb_t server_gaussian_param_p_limbs[] = {2199023255579UL};
static const int_t server_gaussian_param_p = {{(limb_t *)server_gaussian_param_p_limbs, 1, 0}};
static const limb_t server_gaussian_param_pinv_limbs[] = {7727422327118906430UL, 16190UL};
static const int_t server_gaussian_param_pinv = {{(limb_t *)server_gaussian_param_pinv_limbs, 2, 0}};
static const unsigned int server_gaussian_param_s1_indices[76] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75};
static const lin_params_t server_gaussian_param = {{ _server_gaussian_param, 64, server_gaussian_param_p, server_gaussian_param_pinv, 1, server_gaussian_param_s1_indices, 76, NULL, 0,  NULL, 0, server_gaussian_param_Es, server_gaussian_param_Es_nrows, NULL, NULL }};

