// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(41,22,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(11,114,2^(33.629121))
// 
// Ring
// degree d = 64
// modulus q = 36893488147419103693, log(q) ~ 65.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 453378, log(gamma) ~ 18.790355
// 
// Dimensions of secrets
// s1: m1 = 51
// m: l = 0
// s2: m2 = 63
// 
// Size of secrets
// l2(s1) <= alpha = 58.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [51], bounds: [57.131427])
// approximate infinity: yes (psi: 2106.028, dimension: 24, bound: 1632.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 101580.8, log(stdev4/1.55) = 16.0
// 
// Repetition rate
// M1 = 2.9516077
// M2 = 2.6652816
// M3 = 1.0140096
// M4 = 1.0444803
// total = 8.3318994
// 
// Security
// MSIS dimension: 11
// MSIS root hermite factor: 1.0042918
// MLWE dimension: 41
// MLWE root hermite factor: 1.0043564
// 
// Proof size
// ~ 26.9824218750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {461UL, 2UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 2, 0}};
static const limb_t _param_qminus1_limbs[] = {460UL, 2UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 2, 0}};
static const limb_t _param_m_limbs[] = {81374676643814UL, 0UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 2, 0}};
static const limb_t _param_mby2_limbs[] = {40687338321907UL, 0UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 2, 0}};
static const limb_t _param_gamma_limbs[] = {453378UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 2, 0}};
static const limb_t _param_gammaby2_limbs[] = {226689UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 2, 0}};
static const limb_t _param_pow2D_limbs[] = {1024UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 2, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {512UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _param_Bsq_limbs[] = {72024840739156UL, 0UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 4, 0}};
static const limb_t _param_scM1_limbs[] = {6514585634914406712UL, 17554062922924401437UL, 2UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {14122598965936230364UL, 12272279291762237568UL, 2UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {1429323575453357802UL, 258430745254498735UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {7430201332855847487UL, 820516165676486807UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 4, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 4, 0}};
static const limb_t _param_stdev3sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 4, 0}};
static const limb_t _param_stdev4sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 4, 0}};
static const limb_t _param_inv2_limbs[] = {230UL, 1UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 2, 1}};
static const limb_t _param_inv4_limbs[] = {9223372036854775923UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 1, 1}};
static const unsigned int _param_n[1] = {51};
static const limb_t _param_Bz3sqr_limbs[] = {27753065054UL, 0UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _param_Bz4_limbs[] = {1625292UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 2, 0}};
static const limb_t _param_Pmodq_limbs[] = {2728938423809685976UL, 0UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 2, 1}};
static const limb_t _param_l2Bsq0_limbs[] = {3264UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {8644675324563643903UL, 0UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 2, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {7635869008037124735UL, 0UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 2, 1}};
static const limb_t _param_Ppmodq_2_limbs[] = {5041795622675845503UL, 0UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 2, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2};
static const polyring_t _param_ring = {{_param_q, 64, 66, 6, moduli_d64, 3, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 10, 0, 47 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 52, 63, 0, 11, 11, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 52, 63, 9, 2, 11, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 52, 63, 10, 1, 11, _param_Bsq, 1, 8, 5, 140, 1, 16, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 24, 1, 52, 2, 12, _param_scM3, _param_stdev3sq, 2, 16, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 27630UL }};

static const unsigned int param_Es0[51] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50};
static const unsigned int *param_Es[1] = { param_Es0, };
static const unsigned int param_Es_nrows[1] = {51};

static const limb_t param_p_limbs[] = {2199023255579UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {9593674919057203235UL, 0UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 2, 0}};
static const unsigned int param_s1_indices[51] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50};
static const lin_params_t param = {{ _param, 64, param_p, param_pinv, 1, param_s1_indices, 51, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

